### ISSUE TITLE
Receiving errors when trying to run ydict

### ISSUE THREAD

**Issue by rypervenche** [chenpc/ydict#4]
rypervenche@vieux ~ $ ydict --version
ydict 1.3.4

rypervenche@vieux ~ $ python2 --version
Python 2.7.10

rypervenche@vieux ~ $ ydict
<PyDict> test
Traceback (most recent call last):
  File "/usr/local/bin/ydict", line 396, in <module>
    result = dict(word, options.more_exp)
  File "/usr/local/bin/ydict", line 285, in dict
    root = ET.XML(summary)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1300, in XML
    parser.feed(text)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1642, in feed
    self._raiseerror(v)
  File "/usr/lib64/python2.7/xml/etree/ElementTree.py", line 1506, in _raiseerror
    raise err
xml.etree.ElementTree.ParseError: mismatched tag: line 1, column 5039

rypervenche@vieux ~ $ ydict
<PyDict> 測驗
Traceback (most recent call last):
  File "/usr/local/bin/ydict", line 396, in <module>
    result = dict(word, options.more_exp)
  File "/usr/local/bin/ydict", line 313, in dict
    if not isinstance(exp_word.key.text, unicode):
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by bfontaine** [comment]
Same here:

```
$ ydict homebrew
Traceback (most recent call last):
  File "/usr/local/Cellar/ydict/1.3.4/bin/ydict.py", line 364, in <module>
    result=dict(w, options.more_exp)
  File "/usr/local/Cellar/ydict/1.3.4/bin/ydict.py", line 313, in dict
    if not isinstance(exp_word.key.text, unicode):
AttributeError: 'NoneType' object has no attribute 'text'

$ ydict foo
Traceback (most recent call last):
  File "/usr/local/Cellar/ydict/1.3.4/bin/ydict.py", line 364, in <module>
    result=dict(w, options.more_exp)
  File "/usr/local/Cellar/ydict/1.3.4/bin/ydict.py", line 285, in dict
    root = ET.XML(summary)
```
